#!/bin/bash


if [ "$#" -ne "1" ]
then
  echo "Please supply version number"
  exit 1
fi

# pushd ../
# ant test jar
# popd

FOLDER=PolicyModels-$1

mkdir $FOLDER
cp -r ../dist/* $FOLDER/
cp pm $FOLDER/
cp pm.bat $FOLDER/
zip -r release.zip $FOLDER
rm -rf $FOLDER
mv release.zip $FOLDER.zip
